# Generated by Django 4.2.2 on 2023-06-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BooksModel",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("book", models.CharField(max_length=30)),
                ("author", models.CharField(max_length=30)),
                ("genre", models.CharField(max_length=30)),
                ("data", models.DateField()),
            ],
        ),
    ]
