# Generated by Django 4.2.2 on 2023-06-30 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booksmodel",
            old_name="data",
            new_name="date",
        ),
    ]
