# Generated by Django 4.2.2 on 2023-07-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_order_alter_booksmodel_quantity_orderitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
