# Generated by Django 4.2.2 on 2023-07-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_rename_data_booksmodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booksmodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
