# Generated by Django 4.2.2 on 2023-07-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_alter_booksmodel_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
            ],
        ),
    ]
