# Generated by Django 4.2.2 on 2023-07-14 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_usermodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserModel",
        ),
    ]
